collision_controller:
  ros__parameters:
    type: collision_controller/CollisionController
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      - arm_head_1_joint
      - arm_head_2_joint
      - arm_head_3_joint
      - arm_head_4_joint
      - arm_head_5_joint
      - arm_head_6_joint
      - arm_head_7_joint
      - torso_lift_joint
    command_interface: position
