collision_controller:
  ros__parameters:
    type: collision_controller/CollisionController
    update_rate: 1000
    is_async: True
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      - torso_lift_joint
      - gripper_left_thumb_rotatory_joint
      - gripper_left_thumb_flexor_1_joint
      - gripper_left_thumb_flexor_2_joint
      - gripper_left_thumb_flexor_3_joint
      - gripper_left_finger_1_rotatory_joint
      - gripper_left_finger_1_flexor_1_joint
      - gripper_left_finger_1_flexor_2_joint
      - gripper_left_finger_1_flexor_3_joint
      - gripper_left_finger_2_rotatory_joint
      - gripper_left_finger_2_flexor_1_joint
      - gripper_left_finger_2_flexor_2_joint
      - gripper_left_finger_2_flexor_3_joint
      - gripper_left_finger_3_rotatory_joint
      - gripper_left_finger_3_flexor_1_joint
      - gripper_left_finger_3_flexor_2_joint
      - gripper_left_finger_3_flexor_3_joint
      - gripper_right_thumb_rotatory_joint
      - gripper_right_thumb_flexor_1_joint
      - gripper_right_thumb_flexor_2_joint
      - gripper_right_thumb_flexor_3_joint
      - gripper_right_finger_1_rotatory_joint
      - gripper_right_finger_1_flexor_1_joint
      - gripper_right_finger_1_flexor_2_joint
      - gripper_right_finger_1_flexor_3_joint
      - gripper_right_finger_2_rotatory_joint
      - gripper_right_finger_2_flexor_1_joint
      - gripper_right_finger_2_flexor_2_joint
      - gripper_right_finger_2_flexor_3_joint
      - gripper_right_finger_3_rotatory_joint
      - gripper_right_finger_3_flexor_1_joint
      - gripper_right_finger_3_flexor_2_joint
      - gripper_right_finger_3_flexor_3_joint

    publish_mesh: true

    command_interface: position
